// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMfrXVVzzXEEznwBrMXjtNmwZJQ6Liibo',
    appId: '1:75860736721:web:e9ce2fac1814e61f7a23f0',
    messagingSenderId: '75860736721',
    projectId: 'finalexam2-5c330',
    authDomain: 'finalexam2-5c330.firebaseapp.com',
    storageBucket: 'finalexam2-5c330.appspot.com',
    measurementId: 'G-P0E48QLWNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY9xWNcQiEqbh7SgjQZfjZZDEzX01O7kE',
    appId: '1:75860736721:android:b0cb9790297e7b887a23f0',
    messagingSenderId: '75860736721',
    projectId: 'finalexam2-5c330',
    storageBucket: 'finalexam2-5c330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfwAL44l4Ae7ovkJ07xWWHzxrWlpcRrUY',
    appId: '1:75860736721:ios:7e1a2675f21c87dd7a23f0',
    messagingSenderId: '75860736721',
    projectId: 'finalexam2-5c330',
    storageBucket: 'finalexam2-5c330.appspot.com',
    iosBundleId: 'com.example.finalExam2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfwAL44l4Ae7ovkJ07xWWHzxrWlpcRrUY',
    appId: '1:75860736721:ios:7e1a2675f21c87dd7a23f0',
    messagingSenderId: '75860736721',
    projectId: 'finalexam2-5c330',
    storageBucket: 'finalexam2-5c330.appspot.com',
    iosBundleId: 'com.example.finalExam2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMfrXVVzzXEEznwBrMXjtNmwZJQ6Liibo',
    appId: '1:75860736721:web:1d26caf063a97cb67a23f0',
    messagingSenderId: '75860736721',
    projectId: 'finalexam2-5c330',
    authDomain: 'finalexam2-5c330.firebaseapp.com',
    storageBucket: 'finalexam2-5c330.appspot.com',
    measurementId: 'G-N8CGTV32Z0',
  );
}
